### PR TITLE
Openhab 2.4 support

### PR DESCRIPTION
**Pull request by yozik04**

### CODE REVIEW

**Review by mjcumming — APPROVED** [review]

**Comment by yozik04** [comment]
Will you merge it?

**Review by mjcumming — COMMENTED** [review]
There is no need to publish the interval when publishing statistics. The homie only requires the uptime to be published. See https://homieiot.github.io/# 5.2.3.

The only issue here is the timing might be too tight i.e. publishing the update right on time rather than a second or 2 earlier.

**Comment by yozik04** [comment]
According to the spec yes. According to Openhab 2.4 it is required to publish interval... The guy who created the binding made a check on interval. He made a fix but will be only available for Openhab 2.5, which release date is unknown and in a far future.

**Comment by yozik04** [comment]
Thank you. Now we can use it in PAI: https://github.com/jpbarraca/pai/issues/75

**Comment by mjcumming** [comment]
Ok, I removed your code in the current release - add it back if you need it. I haven't had any issues even though OH does complain occasionally.

**Pull request merged**
